name: urqmd
channels:
  - conda-forge
  - nodefaults
dependencies:
  - make
  - c-compiler
  - cxx-compiler
  - fortran-compiler
  - root
  - python=3.11
  - jupyterlab
  - ipykernel
  - matplotlib
  - scipy
  - vim
  - h5py
  - pytorch
  - uproot
